backend:
  name: github
  repo: imran-synectiks/xformation-cms-netlify
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "catalogue"
    label: "Catalogue"
    folder: "src/pages/catalogue"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "catalogue-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: Slider,
          name: slider,
          widget: list,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Name, name: name, widget: text },
              { label: Text, name: text, widget: text },
            ],
        }
  - name: "scenario"
    label: "Scenario"
    folder: "src/pages/scenario"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "scenario-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: Actors List,
          name: scenarios,
          widget: list,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Name, name: name, widget: text },
              {
                label: Use Cases,
                name: subItems,
                widget: list,
                fields:
                  [
                    { label: Image, name: image, widget: image },
                    { label: Name, name: name, widget: text },  
                    {
                      label: Use Case Slider,
                      name: useCaseSlider,
                      widget: list,
                      fields:
                        [
                          { label: Image, name: image, widget: image },
                          { label: Name, name: name, widget: text },
                          { label: Text, name: text, widget: text },                   
                        ]
                    }                 
                  ]
              }
            ]
        }
      - {
          label: Slider,
          name: slider,
          widget: list,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Name, name: name, widget: text },
              { label: Text, name: text, widget: text },
              {
                label: More Details,
                name: moreDetails,
                widget: object,
                fields:
                  [
                    { label: More Details Name, name: moreDetailsName, widget: text },
                    { label: More Details Text, name: moreDetailsText, widget: text },
                    { 
                      label: More Details Image, 
                      name: moreDetailsImage, 
                      widget: list,
                      fields:
                        [
                          { label: Image, name: image, widget: image },
                        ], 
                    },                    
                  ],
              }
            ],
        }
  - name: "service"
    label: "Service"
    folder: "src/pages/service"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "service-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: Page,
          name: page,
          widget: list,
          fields:
            [
              { label: Heading, name: heading, widget: string },
              { label: Description, name: description, widget: text },
            ],
        }
      - {
          label: Testimonials,
          name: testimonials,
          widget: list,
          fields:
            [
              { label: Quote, name: quote, widget: string },
              { label: Author, name: author, widget: string },
            ],
        }
  - name: "workflowpost"
    label: "Workflow Post"
    folder: "src/pages/workflowpost"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "workflow-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Workflow JSON", name: "workflowjson", widget: "object", fields: [{label: Data, name: data, widget: text}]}
  - name: "pagerenderpost"
    label: "PageRender Post"
    folder: "src/pages/pagerenderpost"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-renderer-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "PageRender JSON", name: "pagerendererjson", widget: "object", fields: [{label: Data, name: data, widget: text}]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
      - file: "src/pages/slider/index.md"
        label: "Slider Page"
        name: "slider"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "slider-page",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Slider,
              name: slider,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Name, name: name, widget: text },
                  { label: Text, name: text, widget: text },
                ],
            }
      - file: "src/pages/survey/index.md"
        label: "Survey"
        name: "survey"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "survey-page"}
          - {label: "Survey JSON", name: "surveyjson", widget: "object", fields: [{label: Data, name: data, widget: text}]}
      - file: "src/pages/pagebuilder/index.md"
        label: "Page builder"
        name: "pagebuilder"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-builder-page"}